src/components/page/System/Notice/NoticeMain/NoticeMain.tsx, src/components/page/System/Notice/NoticeMain/styled.ts, src/components/page/System/Notice/NoticeModal/NoticeModal.tsx, src/components/page/System/Notice/NoticeSearch/NoticeSearch.tsx, src/stores/modalState.ts
=> [Notice_250305_jsm]

src/components/common/StyledSelectBox/StyledSelectBox.tsx
=> [code_250306_jsm] 중복 코드 정리

src/api/Provider/SystemProvider.tsx, src/components/page/System/Department/DepartmentMain/DepartmentMain.tsx, src/components/page/System/Department/DepartmentMain/styled.ts, src/components/page/System/Department/DepartmentModal/DepartmentModal.tsx, src/components/page/System/Department/DepartmentModal/styled.ts, src/components/page/System/Department/DepartmentSearch/DepartmentSearch.tsx, src/components/page/System/Department/DepartmentSearch/styled.ts, src/pages/system/Department.tsx, src/routers/Routers.tsx
=> [department_250310_jsm]

src/components/page/System/Notice/NoticeMain/NoticeMain.tsx, src/components/page/System/Notice/NoticeMain/styled.ts, src/components/page/System/Notice/NoticeModal/NoticeModal.tsx, src/components/page/System/Notice/NoticeSearch/NoticeSearch.tsx, src/pages/system/Notice.tsx
=> [notice_250310_jsm] Provider 적용 및 유효성검사 추가, 코드정리

package-lock.json, package.json, src/components/page/Personnel/salaryList/SalaryListMain/SalaryMain.tsx
- 원인 : 사용안하는 icon import로 인해 오류 발생 
- 해결 : import 제거 함
=> [Fix] icon import 제거

package-lock.json, package.json, src/components/page/Personnel/AttendanceList/AttendanceListMain/AttendanceListMain.tsx, src/components/page/Personnel/AttendanceList/AttendanceListMain/styled.ts, src/components/page/Personnel/AttendanceList/AttendanceListModal/AttendanceListModal.tsx, src/components/page/Personnel/AttendanceList/AttendanceListModal/styled.ts, src/pages/personnel/AttendanceList.tsx, src/routers/Routers.tsx
`
npm install @fullcalendar/react @fullcalendar/core @fullcalendar/daygrid
`
=> [attendance-list_250312_jsm]

src/api/SystemApi/postApi.ts, src/api/SystemApi/searchApi.ts, src/api/api.ts, src/components/page/System/Notice/NoticeMain/NoticeMain.tsx, src/components/page/System/Notice/NoticeModal/NoticeModal.tsx, src/components/page/System/Notice/NoticeModal/styled.ts, src/components/page/System/Notice/NoticeSearch/NoticeSearch.tsx, src/components/page/System/Notice/NoticeSearch/styled.ts
=> [notice_250313_jsm] Notice API 모듈화 및 CSS 수정

src/api/api.ts, src/components/page/System/CommonCode/CommonCodeMain/CommonCodeMain.tsx, src/components/page/System/CommonCode/CommonCodeModal/CommonCodeModal.tsx, src/components/page/System/CommonCode/CommonCodeModal/styled.ts, src/components/page/System/CommonCode/CommonCodeSearch/CommonCodeSearch.tsx, src/components/page/System/CommonCode/CommonCodeSearch/styled.ts, src/components/page/System/DetailCode/DetailCodeMain/DetailCodeMain.tsx, src/components/page/System/DetailCode/DetailCodeModal/DetailCodeModal.tsx, src/components/page/System/DetailCode/DetailCodeModal/styled.ts, src/components/page/System/DetailCode/DetailCodeSearch/DetailCodeSearch.tsx, src/components/page/System/DetailCode/DetailModal/DetailModal.tsx, src/pages/system/DetailCode.tsx
=> [code_250313_jsm]

src/api/api.ts, src/components/page/System/Department/DepartmentMain/DepartmentMain.tsx, src/components/page/System/Department/DepartmentModal/DepartmentModal.tsx, src/components/page/System/Department/DepartmentModal/styled.ts, src/components/page/System/Department/DepartmentSearch/DepartmentSearch.tsx, src/components/page/System/Department/DepartmentSearch/styled.ts
=> [department_250313_jsm]

package-lock.json, src/api/api.ts, src/components/page/Personnel/AttendanceRequest/AttendanceRequestMain/AttendanceRequestMain.tsx, src/components/page/Personnel/AttendanceRequest/AttendanceRequestModal/AttendanceRequestModal.tsx, src/components/page/Personnel/AttendanceRequest/AttendanceRequestModal/styled.ts, src/components/page/Personnel/AttendanceRequest/AttendanceRequestRejectModal/AttendanceRequestRejectModal.tsx, src/components/page/Personnel/AttendanceRequest/AttendanceRequestRejectModal/styled.ts, src/components/page/Personnel/AttendanceRequest/AttendanceRequestSearch/AttendanceRequestSearch.tsx, src/components/page/Personnel/AttendanceRequest/AttendanceRequestSearch/styled.ts, src/models/interface/personnel/Attendance/IAttendanceCnt.tsx
=> [attendance-request_250314_jsm]

src/api/PersonnelApi/searchApi.ts, src/api/api.ts, src/components/page/Personnel/AttendanceList/AttendanceListMain/AttendanceListMain.tsx, src/components/page/Personnel/AttendanceList/AttendanceListModal/AttendanceListModal.tsx, src/components/page/Personnel/AttendanceList/AttendanceListModal/styled.ts, src/models/interface/personnel/Attendance/IEvent.tsx
=> [attendance-list_250314_jsm]

src/components/page/System/Notice/NoticeMain/NoticeMain.tsx, src/components/page/System/Notice/NoticeModal/NoticeModal.tsx, src/models/interface/system/Notice/INotice.tsx, src/models/interface/system/Notice/INoticeDetail.tsx
=> [notice_250314_jsm]

src/components/page/System/Department/DepartmentMain/DepartmentMain.tsx, src/components/page/System/Department/DepartmentModal/DepartmentModal.tsx, src/models/interface/system/department/IDepartment.tsx
=> [department_250314_jsm]

src/components/page/System/CommonCode/CommonCodeMain/CommonCodeMain.tsx, src/components/page/System/CommonCode/CommonCodeModal/CommonCodeModal.tsx, src/components/page/System/DetailCode/DetailCodeMain/DetailCodeMain.tsx, src/components/page/System/DetailCode/DetailCodeModal/DetailCodeModal.tsx, src/components/page/System/Notice/NoticeMain/NoticeMain.tsx, src/models/interface/system/commoncode/IDetailCode.tsx, src/models/interface/system/commoncode/IDetailCodeDetail.tsx, src/models/interface/system/commoncode/IGroupCode.tsx
=> [code_250314_jsm]

src/components/page/Business/Sales/SalesPlan/SalesPlanListMain/SalesPlanMain.tsx, src/components/page/Business/Sales/SalesPlan/SalesPlanModal/SalesPlanListModal.tsx, src/components/page/Business/Sales/SalesPlan/SalesPlanSearch/SalesPlanListSearch.tsx, src/models/interface/business/sales/ISales.tsx
=> ISales 경로 재지정

src/components/page/Personnel/AttendanceRequest/AttendanceRequestMain/AttendanceRequestMain.tsx, src/components/page/Personnel/AttendanceRequest/AttendanceRequestSearch/AttendanceRequestSearch.tsx
=> [attendance-request_250317_jsm]

src/components/page/System/Notice/NoticeModal/NoticeModal.tsx, src/components/page/System/Notice/NoticeModal/styled.ts, src/components/page/System/Notice/NoticeSearch/NoticeSearch.tsx
=> [notice_250317_jsm]

src/components/page/Personnel/AttendanceRequest/AttendanceRequestMain/AttendanceRequestMain.tsx, src/models/interface/personnel/attendance/IAttendanceCnt.tsx
=> [attendance-request_250318_jsm] 

src/components/page/Personnel/AttendanceApproval/AttendanceApprovalModal/AttendanceApprovalModal.tsx, src/components/page/Personnel/AttendanceRequest/AttendanceRequestModal/AttendanceRequestModal.tsx
=> [attendance_250318_jsm] 등록 폼 입력 필드 개선

src/components/page/Business/Sales/SalesResult/SalesResultListSearch/SalesResultListSearch.tsx
SalesResultListSearch option의 value 수정 ->manuFacturerOptions(manuFacturerValue.industryCode)
=> merge into dev from fix/sales-result_cwm_250318 branch

src/components/page/Business/Client/ClientList/ClientListMain/ClientListMain.tsx, src/components/page/Business/Client/ClientList/ClientListModal/ClientListModal.tsx, src/components/page/Business/Client/ClientList/ClientListModal/styled.ts, src/components/page/Business/Client/ClientList/ClientListSearch/ClientListSearch.tsx, src/components/page/Business/Sales/SalesPlan/SalesPlanListMain/SalesPlanMain.tsx, src/components/page/Business/Sales/SalesPlan/SalesPlanModal/SalesPlanListModal.tsx
=> merge into dev from client-list_modal_250318 branch

src/components/page/Business/Estimate/EstimateList/EstimateListMain/EstimateListMain.tsx, src/components/page/Business/Estimate/EstimateList/EstimateListModal/EstimateListModal.tsx, src/components/page/Business/Estimate/EstimateList/EstimateListModal/styled.ts, src/components/page/Business/Estimate/EstimateList/EstimateListSearch/EstimateListSearch.tsx, src/components/page/Business/Order/OrderList/OrderListModal/OrderListModal.tsx
Estimate list modal 250320 cwm
=> merge into dev from estimate-list_modal_250320_cwm branch

src/components/page/System/Department/DepartmentModal/DepartmentModal.tsx
=> [department_250320_jsm]

src/components/page/Personnel/AttendanceApproval/AttendanceApprovalModal/AttendanceApprovalModal.tsx
=> [attendance-approval_250320_jsm] 

src/components/page/Business/Order/OrderList/OrderListMain/OrderListMain.tsx, src/components/page/Business/Order/OrderList/OrderListModal/OrderListModal.tsx, src/components/page/Business/Order/OrderList/OrderListSearch/OrderListSearch.tsx, src/pages/business/OrderList.tsx
Fix/order information list modal 250321 cwm
=> merge into dev from fix/order-information-list_modal_250319_cwm branch

src/components/page/Business/Estimate/EstimateList/EstimateListMain/EstimateListMain.tsx, src/components/page/Business/Estimate/EstimateList/EstimateListModal/EstimateListModal.tsx
Estimate list modal 250320 cwm
=> merge into dev estimate-list_modal_250320_cwm branch

src/components/page/Business/Sales/SalesPlan/SalesPlanListMain/SalesPlanMain.tsx, src/models/interface/business/sales/ISales.tsx
=> [sales-plan_250321_jsm] SalesPlanList: 페이징 추가

src/components/page/Business/Client/ClientList/ClientListMain/ClientListMain.tsx, src/components/page/Business/Client/ClientList/ClientListModal/ClientListModal.tsx, src/components/page/Business/Client/ClientList/ClientListSearch/ClientListSearch.tsx
Fix/client list modal 250321 cwm
=> merge into dev from fix/client-list_modal_250321_cwm branch

src/components/page/Business/Sales/SalesResult/SalesResultListMain/SalesResultListMain.tsx
=> [sales-list_250321_jsm] SalesResultList: 페이징 추가

src/components/page/Business/Client/ClientList/ClientListMain/ClientListMain.tsx, src/components/page/Business/Client/ClientList/ClientListMain/styled.ts
=> [client-list_250321_jsm] 페이징 처리

src/components/page/Account/ExpenseList/ExpenseListMain/ExpenseListMain.tsx, src/pages/account/ExpenseList.tsx
=> [expense-list_250321_jsm] 

src/components/page/Business/Client/ClientList/ClientListMain/ClientListMain.tsx, src/components/page/Business/Client/ClientList/ClientListModal/ClientListModal.tsx, src/components/page/Business/Sales/SalesPlan/SalesPlanListMain/SalesPlanMain.tsx, src/components/page/Business/Sales/SalesPlan/SalesPlanListMain/styled.ts, src/components/page/Business/Sales/SalesPlan/SalesPlanModal/SalesPlanListModal.tsx, src/components/page/Business/Sales/SalesPlan/SalesPlanModal/styled.ts, src/components/page/Business/Sales/SalesPlan/SalesPlanSearch/SalesPlanListSearch.tsx, src/components/page/Business/Sales/SalesResult/SalesResultListSearch/SalesResultListSearch.tsx, src/pages/business/SalesPlanList.tsx
Fix/sales plan modal 250320 cwm
=> merge info dev from fix/sales-plan_modal_250320_cwm branch

.gitignore, src/components/page/Account/ExpenseApproval/ExpenseApprovalModal/ExpenseApprovalModal.tsx
=> [Expense-approval_250321_jsm]

src/components/page/Business/Client/ClientList/ClientListSearch/ClientListSearch.tsx, src/components/page/Business/Estimate/EstimateList/EstimateListModal/styled.ts, src/components/page/Business/Estimate/EstimateList/EstimateListSearch/EstimateListSearch.tsx, src/components/page/Business/Order/OrderList/OrderListModal/styled.ts, src/components/page/Business/Order/OrderList/OrderListSearch/OrderListSearch.tsx
Fix/order information list modal 250321 cwm
=> merge into dev from fix/order-information-list_modal_250321_cwm branch
